"""initial_migration_simplified

Revision ID: 11622d710e83
Revises:
Create Date: 2026-01-17 20:08:46.883414

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11622d710e83"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("parent_document_id", sa.Integer(), nullable=True),
        sa.Column("is_composite", sa.Integer(), server_default="0", nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_text_tesseract", sa.Text(), nullable=True),
        sa.Column("ocr_text_ollama", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.String(length=50), nullable=True),
        sa.Column("ocr_completed_at", sa.DateTime(), nullable=True),
        sa.Column("ocr_text_final", sa.Text(), nullable=True),
        sa.Column(
            "document_type",
            sa.Enum(
                "MEETING_PROTOCOL",
                "INVITATION",
                "PHOTO",
                "MEMBER_LIST",
                "FINANCIAL_REPORT",
                "OTHER",
                name="documenttype",
            ),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "OCR_PENDING",
                "OCR_DONE",
                "REVIEW_PENDING",
                "REVIEWED",
                "CLASSIFIED",
                "ANNOTATED",
                "PUBLISHED",
                name="documentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_date"), "documents", ["date"], unique=False)
    op.create_index(
        op.f("ix_documents_file_path"), "documents", ["file_path"], unique=False
    )
    op.create_index(
        op.f("ix_documents_filename"), "documents", ["filename"], unique=False
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_index(
        op.f("ix_documents_parent_document_id"),
        "documents",
        ["parent_document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_table(
        "document_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_metadata_document_id"),
        "document_metadata",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_metadata_id"), "document_metadata", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_document_metadata_key"), "document_metadata", ["key"], unique=False
    )
    op.create_table(
        "document_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("is_extracted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_pages_document_id"),
        "document_pages",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_pages_id"), "document_pages", ["id"], unique=False
    )
    op.create_table(
        "ocr_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("document_page_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="ocrjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("use_correction", sa.Boolean(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("current_step", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_page_id"],
            ["document_pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ocr_jobs_document_id"), "ocr_jobs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_ocr_jobs_document_page_id"),
        "ocr_jobs",
        ["document_page_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ocr_jobs_id"), "ocr_jobs", ["id"], unique=False)
    op.create_index(op.f("ix_ocr_jobs_status"), "ocr_jobs", ["status"], unique=False)
    op.create_table(
        "ocr_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("document_page_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "TESSERACT",
                "OLLAMA_VISION",
                "GPT_CORRECTED",
                "MANUAL",
                "COMBINED",
                name="ocrsource",
            ),
            nullable=False,
        ),
        sa.Column("engine_version", sa.String(length=50), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("confidence_details", sa.JSON(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_page_id"],
            ["document_pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ocr_results_document_id"), "ocr_results", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_ocr_results_document_page_id"),
        "ocr_results",
        ["document_page_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ocr_results_id"), "ocr_results", ["id"], unique=False)
    op.create_index(
        op.f("ix_ocr_results_source"), "ocr_results", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ocr_results_source"), table_name="ocr_results")
    op.drop_index(op.f("ix_ocr_results_id"), table_name="ocr_results")
    op.drop_index(op.f("ix_ocr_results_document_page_id"), table_name="ocr_results")
    op.drop_index(op.f("ix_ocr_results_document_id"), table_name="ocr_results")
    op.drop_table("ocr_results")
    op.drop_index(op.f("ix_ocr_jobs_status"), table_name="ocr_jobs")
    op.drop_index(op.f("ix_ocr_jobs_id"), table_name="ocr_jobs")
    op.drop_index(op.f("ix_ocr_jobs_document_page_id"), table_name="ocr_jobs")
    op.drop_index(op.f("ix_ocr_jobs_document_id"), table_name="ocr_jobs")
    op.drop_table("ocr_jobs")
    op.drop_index(op.f("ix_document_pages_id"), table_name="document_pages")
    op.drop_index(op.f("ix_document_pages_document_id"), table_name="document_pages")
    op.drop_table("document_pages")
    op.drop_index(op.f("ix_document_metadata_key"), table_name="document_metadata")
    op.drop_index(op.f("ix_document_metadata_id"), table_name="document_metadata")
    op.drop_index(
        op.f("ix_document_metadata_document_id"), table_name="document_metadata"
    )
    op.drop_table("document_metadata")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_parent_document_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_filename"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_path"), table_name="documents")
    op.drop_index(op.f("ix_documents_date"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
